set(CGET_PREFIX "/Users/mihau/workspace/geo-proj/cget")
set(CMAKE_PREFIX_PATH "/Users/mihau/workspace/geo-proj/cget")
include_directories(SYSTEM ${CMAKE_PREFIX_PATH}/include)
if (CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT)
    set(CMAKE_INSTALL_PREFIX "/Users/mihau/workspace/geo-proj/cget")
endif()
